import {ReactNode} from 'react'
import Head from 'next/head'
import {useSession} from 'next-auth/react'
import {styled} from '@mui/material/styles'
import {Box} from '@mui/material'

import {PageHeader} from '../PageHeader'

type Props = {
    children: ReactNode
}

export const PageLayaut = ({children}: Props) => {
    const {data: session} = useSession()

    return (
        <Wrapper>
            <Background />
            <InnerWrapper>
                <Head>
                    <title>Create Next App</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                {session && <PageHeader />}

                {children}
            </InnerWrapper>
        </Wrapper>
    )
}

const Wrapper = styled(Box)`
    position: relative;
    height: 100vh;
    width: 100vw;
`

const InnerWrapper = styled(Box)`
    position: relative;
    height: 100%;
    width: 100%;
`

const Background = styled(Box)`
    background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
    background-size: 400% 400%;
    animation: gradient 15s ease infinite;
    height: calc(100vh + 200px);
    width: calc(100vw + 200px);
    padding: 100px;
    position: fixed;
    top: -100px;
    left: -100px;

    @keyframes gradient {
        0% {
            background-position: 0% 50%;
        }
        50% {
            background-position: 100% 50%;
        }
        100% {
            background-position: 0% 50%;
        }
    }
`
